# Generated by Django 2.2.1 on 2019-12-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('mes_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('rather', 'RatherNotSay')], default='male', max_length=10)),
                ('selphone', models.CharField(choices=[('91', '+91'), ('92', '+92'), ('93', '+93'), ('94', '+94'), ('95', '+95'), ('96', '+96')], default='91', max_length=10)),
                ('contactnumber', models.CharField(default='', max_length=10)),
                ('password', models.CharField(default='', max_length=20)),
                ('cpassword', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
