# Generated by Django 2.2.1 on 2019-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicineordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineordered',
            name='totalSum',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
