# Generated by Django 2.2.1 on 2019-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20191208_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineordered',
            name='Ashwagandha',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Chyawanprash',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Cofsils',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Combiflam',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Crocin',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Dettol',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='DigeneGel',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='DigeneTablet',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Hajmola',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Lubrifresh',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Moov',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Paracetamol',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Seacod',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Shelcal',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Vicks',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicineordered',
            name='Zandu',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
