# Generated by Django 2.2.1 on 2019-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_auto_20191208_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineordered',
            name='emaill',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
