# Generated by Django 2.2.1 on 2019-12-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_remove_medicineordered_emaill'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineordered',
            name='storeemail',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
