# Generated by Django 2.2.1 on 2019-12-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_medicineordered_storeemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Askdoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
                ('looking', models.CharField(max_length=20)),
                ('email', models.EmailField(default='null', max_length=254)),
                ('selphone', models.CharField(choices=[('91', '+91'), ('92', '+92'), ('93', '+93'), ('94', '+94'), ('95', '+95'), ('96', '+96')], default='91', max_length=10)),
                ('contactnumber', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
