# Generated by Django 2.2.1 on 2019-12-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_askdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askdoctor',
            name='looking',
            field=models.CharField(choices=[('information', 'Just Information'), ('details', 'Treatment Details')], default='information', max_length=20),
        ),
    ]
