# Generated by Django 2.2.1 on 2019-12-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_auto_20191209_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='null', max_length=200)),
                ('message', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='askdoctor',
            name='looking',
            field=models.CharField(choices=[('Just Information', 'Just Information'), ('Treatment Details', 'Treatment Details')], default='information', max_length=20),
        ),
    ]
