# Generated by Django 2.2.1 on 2019-12-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_auto_20191210_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineordered',
            name='Combiflam',
            field=models.IntegerField(default=0),
        ),
    ]
