# Generated by Django 2.2.1 on 2019-12-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_auto_20191210_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
