# Generated by Django 3.0.6 on 2020-05-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_registration_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Askdoctor',
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('rather', 'Non binary')], default='male', max_length=10),
        ),
    ]
